<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUzbRyQR\Oesteve_Tests_Transformer_Symfony_TestKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUzbRyQR/Oesteve_Tests_Transformer_Symfony_TestKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerUzbRyQR.legacy');

    return;
}

if (!\class_exists(Oesteve_Tests_Transformer_Symfony_TestKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerUzbRyQR\Oesteve_Tests_Transformer_Symfony_TestKernelTestDebugContainer::class, Oesteve_Tests_Transformer_Symfony_TestKernelTestDebugContainer::class, false);
}

return new \ContainerUzbRyQR\Oesteve_Tests_Transformer_Symfony_TestKernelTestDebugContainer([
    'container.build_hash' => 'UzbRyQR',
    'container.build_id' => '631416a3',
    'container.build_time' => 1632072060,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUzbRyQR');
