<?php

namespace ContainerUzbRyQR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransformerService extends Oesteve_Tests_Transformer_Symfony_TestKernelTestDebugContainer
{
    /**
     * Gets the public 'Oesteve\Transformer\Transformer' shared service.
     *
     * @return \Oesteve\Transformer\Transformer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/Transformer.php';
        include_once \dirname(__DIR__, 5).'/lib/Middleware/Middleware.php';
        include_once \dirname(__DIR__, 5).'/lib/Middleware/ResolverMiddleware.php';
        include_once \dirname(__DIR__, 5).'/lib/ResolverLocator.php';
        include_once \dirname(__DIR__, 5).'/lib/ResolverLocator/SymfonyResolverLocator.php';

        return $container->services['Oesteve\\Transformer\\Transformer'] = new \Oesteve\Transformer\Transformer(new \Oesteve\Transformer\Middleware\ResolverMiddleware(new \Oesteve\Transformer\ResolverLocator\SymfonyResolverLocator(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Oesteve\\Tests\\Transformer\\Dto\\UserDto' => ['services', 'Oesteve\\Tests\\Transformer\\Dto\\UserResolver', 'getUserResolverService', true],
        ], [
            'Oesteve\\Tests\\Transformer\\Dto\\UserDto' => '?',
        ]))));
    }
}
