<?php

namespace ContainerUzbRyQR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserResolverService extends Oesteve_Tests_Transformer_Symfony_TestKernelTestDebugContainer
{
    /**
     * Gets the public 'Oesteve\Tests\Transformer\Dto\UserResolver' shared service.
     *
     * @return \Oesteve\Tests\Transformer\Dto\UserResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/Resolver.php';
        include_once \dirname(__DIR__, 4).'/Dto/UserResolver.php';

        return $container->services['Oesteve\\Tests\\Transformer\\Dto\\UserResolver'] = new \Oesteve\Tests\Transformer\Dto\UserResolver();
    }
}
